version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: lemo_lantu_secret_666
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: lemo_lantu_admin
            password: lemo_lantu
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: lemo_lantu_admin
      POSTGRES_PASSWORD: lemo_lantu
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: ~